// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/supplier-activity-current/Current.tsx": () => import("../components/mockups/supplier-activity-current/Current.tsx"),
  "./components/mockups/supplier-allocation-activity/SupplierActivity.tsx": () => import("../components/mockups/supplier-allocation-activity/SupplierActivity.tsx"),
  "./components/mockups/supplier-allocation-activity/SupplierDateActivity.tsx": () => import("../components/mockups/supplier-allocation-activity/SupplierDateActivity.tsx")
};
